### ISSUE TITLE
Fatal Exception: com.facebook.react.bridge.ObjectAlreadyConsumedException: Map already consumed

### ISSUE THREAD

**Issue by MaxTibs** [innoveit/react-native-ble-manager#1102]
Hi I'd like some help to resolve an occasional crash that is happening on a Android Pixel 8 Pro. 

**Describe the bug**
```
Fatal Exception: com.facebook.react.bridge.ObjectAlreadyConsumedException: Map already consumed
       at com.facebook.react.bridge.WritableNativeArray.pushNativeMap(WritableNativeArray.java)
       at com.facebook.react.bridge.WritableNativeArray.pushMap(WritableNativeArray.java:57)
       at com.facebook.react.bridge.Arguments.fromJavaArgs(Arguments.java:183)
       at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:31)
       at it.innove.Peripheral.lambda$onServicesDiscovered$2$it-innove-Peripheral(Peripheral.java:296)
       at it.innove.Peripheral$$ExternalSyntheticLambda0.run(:4)
       at android.os.Handler.handleCallback(Handler.java:958)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loopOnce(Looper.java:205)
       at android.os.Looper.loop(Looper.java:294)
       at android.app.ActivityThread.main(ActivityThread.java:8177)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:971)
```

**To Reproduce**
I don't know how to reproduce. It seems random while the phone is connecting.

**Expected behavior**
Application shouldn't crash randomly because of the issue described above

**Smartphone (please complete the following information):**
 - Device: Android Pixel 8 Pro
 - OS: 14
 - react-native-ble-manager version: 10.1.2
 - react-native version: 0.72.4

Thanks for your help

**Comment by RijanFedo** [comment]
![image](https://github.com/innoveit/react-native-ble-manager/assets/88964327/d46dac70-4780-441e-a517-88715ccb2f6a)
Also receiving the same error. @MaxTibs did you find any fix for this ???
