### ISSUE TITLE
App crashes after Update

### ISSUE THREAD

**Issue by akucharczyk** [innoveit/react-native-ble-manager#1112]
**Describe the bug**
On android 12 the App crashes after start

**To Reproduce**
Just start the App, with implementation

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi 10
 - OS: Android 12
 - react-native-ble-manager version:  11.0.1
 - react-native version: 0.72.7

**Additional context**
`
FATAL EXCEPTION: Binder:29110_2

java.lang.NoSuchMethodError: No super method onCharacteristicChanged(Landroid/bluetooth/BluetoothGatt;Landroid/bluetooth/BluetoothGattCharacteristic;[B)V in class Landroid/bluetooth/BluetoothGattCallback; or its super classes (declaration of 'android.bluetooth.BluetoothGattCallback' appears in /system/framework/framework.jar)

FATAL EXCEPTION: Binder:29110_2
Process: com.trotec.troteccontrol, PID: 29110
java.lang.NoSuchMethodError: No super method onCharacteristicChanged(Landroid/bluetooth/BluetoothGatt;Landroid/bluetooth/BluetoothGattCharacteristic;[B)V in class Landroid/bluetooth/BluetoothGattCallback; or its super classes (declaration of 'android.bluetooth.BluetoothGattCallback' appears in /system/framework/framework.jar)
	at it.innove.Peripheral.onCharacteristicChanged(Peripheral.java:427)
	at it.innove.Peripheral.onCharacteristicChanged(Peripheral.java:422)
	at android.bluetooth.BluetoothGatt$1$8.run(BluetoothGatt.java:490)
	at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:823)
	at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:47)
	at android.bluetooth.BluetoothGatt$1.onNotify(BluetoothGatt.java:484)
	at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:315)
	at android.os.Binder.execTransactInternal(Binder.java:1187)
	at android.os.Binder.execTransact(Binder.java:1146)`

**Comment by marcosinigaglia** [comment]
Hi @akucharczyk , try https://github.com/innoveit/react-native-ble-manager/releases/tag/v.11.0.2
