### ISSUE TITLE
DiscoverPeripheral causes ConcurrentModificationException on Android

### ISSUE THREAD

**Issue by jussisaurio** [innoveit/react-native-ble-manager#153]
- react-native-ble-manager v. latest
- react-native v0.44

Seems to happen randomly when scanning is active. I noticed that the BleManagerDiscoverPeripheral event gets fired multiple times per device upon discovery.

```
05-18 14:22:08.598 21890  5142 D logs    : Get discovered peripherals

05-18 14:22:08.599 21890 21890 I logs    : DiscoverPeripheral: null

05-18 14:22:08.602 21890  5142 E unknown:React: Exception in native call

05-18 14:22:08.602 21890  5142 E unknown:React: java.util.ConcurrentModificationException

05-18 14:22:08.602 21890  5142 E unknown:React: 	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:375)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:373)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at it.innove.BleManager.getDiscoveredPeripherals(BleManager.java:352)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at java.lang.reflect.Method.invoke(Native Method)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:368)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:138)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at android.os.Handler.handleCallback(Handler.java:739)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at android.os.Handler.dispatchMessage(Handler.java:95)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at android.os.Looper.loop(Looper.java:148)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:208)

05-18 14:22:08.602 21890  5142 E unknown:React: 	at java.lang.Thread.run(Thread.java:818)
```

**Comment by marcosinigaglia** [comment]
Hi, I think the problem is that you call getDiscoveredPeripherals while is scanning.
