### ISSUE TITLE
retrieveServices never returns after disabling and enabling ble from device settings

### ISSUE THREAD

**Issue by anwarhamr** [innoveit/react-native-ble-manager#366]
### 
    "react-native-ble-manager": "^6.5.0",
    "react": "16.3.1",
    "react-native": "0.55.4",
    Android for now, will verify iOS soon (but I don't think it's a problem)

### Expected behaviour
Get the services like it does the first time when my app starts and is connected.

### Actual behaviour
hangs and never returns.

### Steps to reproduce

1. Start android app using lib
2. connect to a device and retrieveServices; works great.
3. leave app running and go to ble settings on phone turn off and back on
4. wait for notification that BleManagerDidUpdateState to be `on`
5. scan for devices
6. device is found again via scan
7. call connect(); connects just fine
8. call retrieveServices() it never returns...

```
  connect(peripheral) {
    this.log.warn('BLE Connect reqeusted', peripheral);
      return BleManager.connect(peripheral)
      .then(()=>{
        this.log.warn('BLE Connected to', peripheral);
        return BleManager.retrieveServices(peripheral) //<-- never returns after first success.
          .then(peripheralInfo=>{
            this.log.warn('BLE Service info:' ,peripheralInfo);
            return Promise.resolve(peripheralInfo);
          });});
     }
```
While connected to android studio I see this message
```

08-02 17:16:55.804 26397-26683/com.aura_react_native D/ReactNativeBleManager: Retrieve services from: 80:EA:CA:70:01:00
08-02 17:16:55.804 26397-26683/com.aura_react_native D/BluetoothGatt: discoverServices() - device: 80:EA:CA:70:01:00
08-02 17:16:55.810 26397-26683/com.aura_react_native E/BluetoothGatt: android.os.DeadObjectException
                                                                          at android.os.BinderProxy.transactNative(Native Method)
                                                                          at android.os.BinderProxy.transact(Binder.java:802)
                                                                          at android.bluetooth.IBluetoothGatt$Stub$Proxy.discoverServices(IBluetoothGatt.java:1406)
                                                                          at android.bluetooth.BluetoothGatt.discoverServices(BluetoothGatt.java:933)
                                                                          at it.innove.Peripheral.retrieveServices(Peripheral.java:626)
                                                                          at it.innove.BleManager.retrieveServices(BleManager.java:313)
                                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                                          at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
                                                                          at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:160)
                                                                          at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
                                                                          at android.os.Handler.handleCallback(Handler.java:790)
                                                                          at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:29)
                                                                          at android.os.Looper.loop(Looper.java:164)
                                                                          at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:192)
                                                                          at java.lang.Thread.run(Thread.java:764)
```

**Comment by JJSrra** [comment]
Having a similar issue in iOS, reproducing the same steps, but instead of step 8 it throws a "Peripheral not found or not connected" error.

@anwarhamr @marcosinigaglia Any news on that?

**Comment by anwarhamr** [comment]
@JJSrra I have not had a chance to validate w/ my iOS device.  I'll try to get to it this week.

**Comment by JJSrra** [comment]
@marcosinigaglia Please could you take a look at that? Seems like a bug and is quite annoying as the library works fine until it gets to this point... Thanks in advance!

@anwarhamr Did you test it on your iOS device? Any news? 🙂

**Comment by anwarhamr** [comment]
@JJSrra This is not happening on my ios devices.

**Comment by JJSrra** [comment]
I'm also rescanning the same way you do @anwarhamr (as reported in the issue) but it doesn't seem to work. First connection when I start the app is always successful, and even first reconnection after disconnecting is successful most of the times, but then second reconnection hardly ever works, it just throws the "Peripheral not found or not connected" even though the app still connects to the device. Given the fact that I'm able to reconnect once, I assume that my code has a good structure and there has to be something else.

Related to your issue with Android, have you tried using the `refreshCache` method? It's an Android-only method but perhaps is related to this since it refreshes the peripheral's services and characteristics.

**Comment by nagaokashi** [comment]
#391

**Comment by nagaokashi** [comment]
>  then second reconnection hardly ever works, it just throws the "Peripheral not found or not connected" even though the app still connects to the device. 

Did you check  `getConnectedPeripherals ` at the second reconnection? If no, I think you should try.

**Comment by JJSrra** [comment]
Hi everyone, sorry for the late response.

@nagaokashi I tried to connect and then check the `getConnectedPeripherals` value and it always returns the expected value (the device I'm looking for), even at the second reconnection in which `retrieveServices` fails. As I said, it works fine the very first time, and even the first time I try to reconnect. The library is able to connect to the device and retrieve the services, but sadly the second time hardly ever works ☹️

The above happens if I create a new `BleManager` instance each time I try to connect, calling `BleManager.start()`. If I disconnect from a device and then try to connect to the same device several times (without "restarting" BleManager) it works, but it fails if I try to connect to more than one BleManager instance, i.e. when I try to connect to several devices in the same app. Switching between devices works once or twice, but the next time I get the same wrong behaviour after calling `retrieveServices`.

@marcosinigaglia Any updates on this? Could you work on it on past months?

**Comment by anwarhamr** [comment]
I have not seen this issue in a long time.  My pattern is to always call `getConnectedPeripherals` check that list for my client, if it's not there I call `connect`.  This is working for me.
