### ISSUE TITLE
/example directory missing from install...

### ISSUE THREAD

**Issue by dmorr041** [innoveit/react-native-ble-manager#421]
### Version

Tell us which versions you are using:

- react-native-ble-manager v^6.5.4
- react-native v0.57.4
- Android v.27

### Expected behaviour

The directory 'react-native-ble-manager/example/App' should exist, but after installing via npm and linking manually, the example directory is not there. I simply want to run the example.

### Actual behaviour

The library installs but without the example directory.

### Steps to reproduce

1. npm install react-native-ble-manager from command line in project root directory.
2. Manually link for Android
3. Add the following code to index.js and run the example:

`import React, { Component } from 'react';`
`import {`
  `AppRegistry,`
`} from 'react-native';`
`import App from 'react-native-ble-manager/example/App' //<-- simply point to the example js!`

`AppRegistry.registerComponent('MyAwesomeApp', () => App);`

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

error: bundling failed: Error: Unable to resolve module `react-native-ble-manager/example/App` from `C:\RengTech\Coconut\React\CoconutReact\Coconut\index.js`: Module `react-native-ble-manager/example/App` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:139:15)
    at ResolutionRequest.resolveDependency (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\node-haste\DependencyGraph.js:219:16)
    at Object.resolve (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\lib\transformHelpers.js:141:30)
    at dependencies.map.result (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\DeltaBundler\traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\DeltaBundler\traverseDependencies.js:369:18)
    at C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\DeltaBundler\traverseDependencies.js:188:33    at Generator.next (<anonymous>)
    at step (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\DeltaBundler\traverseDependencies.js:298:30)
 DELTA  [android, dev] ..\..\../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::1 - - [17/Dec/2018:20:03:35 +0000] "GET /index.delta?platform=android&dev=true&minify=false HTTP/1.1" 500 - "http://localhost:8081/debugger-ui/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
 DELTA  [android, dev] ..\..\../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

 MAP  [android, dev] ..\..\../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1)::1 - - [17/Dec/2018:20:03:36 +0000] "GET /index.map?platform=android&dev=true&minify=false&deltaBundleId=bfa13889bdd1ffc1 HTTP/1.1" 500 - "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.110 Safari/537.36"
error: bundling failed: Error: Unable to resolve module `react-native-ble-manager/example/App` from `C:\RengTech\Coconut\React\CoconutReact\Coconut\index.js`: Module `react-native-ble-manager/example/App` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:139:15)
    at ResolutionRequest.resolveDependency (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\node-haste\DependencyGraph\ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\node-haste\DependencyGraph.js:219:16)
    at Object.resolve (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\lib\transformHelpers.js:141:30)
    at dependencies.map.result (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\DeltaBundler\traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\DeltaBundler\traverseDependencies.js:369:18)
    at C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\DeltaBundler\traverseDependencies.js:188:33    at Generator.next (<anonymous>)
    at step (C:\RengTech\Coconut\React\CoconutReact\Coconut\node_modules\metro\src\DeltaBundler\traverseDependencies.js:298:30)
 MAP  [android, dev] ..\..\../index.js ░░░░░░░░░░░░░░░░ 0.0% (0/1), failed.

```
```

**Comment by marcosinigaglia** [comment]
Hi, you have to clone the repo to use the example, is removed from the npm package.
