### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.le.ScanResult.isConnectable()' on a null object reference

### ISSUE THREAD

**Issue by fermuch** [innoveit/react-native-ble-manager#756]
### Version

- react-native-ble-manager v7.6.0
- react-native v0.64.2
- Android 8

### Expected behaviour

No error is shown.

### Actual behaviour

An error is displayed on logcat (NOT on react-native)

### Steps to reproduce

1. connect to a device mac directly, without scanning first
2. problem is shown

### Stack trace and console log

```
07-09 15:06:09.847 11852 15159 D BluetoothManager: getConnectedDevices
07-09 15:06:09.859 11852 15159 W System.err: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.bluetooth.le.ScanResult.isConnectable()' on a null object reference
07-09 15:06:09.860 11852 15159 W System.err:    at it.innove.LollipopPeripheral.asWritableMap(LollipopPeripheral.java:44)
07-09 15:06:09.860 11852 15159 W System.err:    at it.innove.BleManager.getConnectedPeripherals(BleManager.java:621)
07-09 15:06:09.861 11852 15159 W System.err:    at java.lang.reflect.Method.invoke(Native Method)
07-09 15:06:09.861 11852 15159 W System.err:    at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
07-09 15:06:09.862 11852 15159 W System.err:    at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151)
07-09 15:06:09.862 11852 15159 W System.err:    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
07-09 15:06:09.862 11852 15159 W System.err:    at android.os.Handler.handleCallback(Handler.java:790)
07-09 15:06:09.862 11852 15159 W System.err:    at android.os.Handler.dispatchMessage(Handler.java:99)
07-09 15:06:09.862 11852 15159 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
07-09 15:06:09.862 11852 15159 W System.err:    at android.os.Looper.loop(Looper.java:164)
07-09 15:06:09.862 11852 15159 W System.err:    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
07-09 15:06:09.862 11852 15159 W System.err:    at java.lang.Thread.run(Thread.java:764)
```

-----------

It seems like [LollipopPeripheral](https://github.com/innoveit/react-native-ble-manager/blob/master/android/src/main/java/it/innove/LollipopPeripheral.java#L44) calls `scanResult` without checking if it is set, throwing the error before on logcat.

Since there is no scan, `scanResult` is `null` in that case.

**Comment by jimhuf** [comment]
any update on this issue?
