### ISSUE TITLE
java.lang.RuntimeException it.innove.BleManager$1.onActivityResult

### ISSUE THREAD

**Issue by iAmHarmon** [innoveit/react-native-ble-manager#769]
### Before open an issue
- Check the closed issues, your question maybe is not new.
- We can't debug your physical devices.
- If the library is not working 99% you did something wrong, in the code or in the phone permissions.

### Version

Tell us which versions you are using:

- react-native-ble-manager v7.6.0
- react-native v0.63.4
- Android v11

### Expected behaviour

Tell us what should happen
App does not crash

### Actual behaviour

Tell us what happens instead
App is crashing in production

### Steps to reproduce
Unknown as this is happening in production.

### Stack trace and console log

Hint: it would help a lot if you enable the debugger ("Pause on exceptions" in the "Source" panel of Chrome dev tools) and spot the place where the error is thrown

```
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
    at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:26)
    at it.innove.BleManager$1.onActivityResult(BleManager.java:86)
    at com.facebook.react.bridge.ReactContext.onActivityResult(ReactContext.java:308)
    at com.facebook.react.ReactInstanceManager.onActivityResult(ReactInstanceManager.java:758)
    at com.facebook.react.ReactDelegate.onActivityResult(ReactDelegate.java:90)
    at com.facebook.react.ReactActivityDelegate.onActivityResult(ReactActivityDelegate.java:112)
    at com.facebook.react.ReactActivity.onActivityResult(ReactActivity.java:68)
    at android.app.Activity.dispatchActivityResult(Activity.java:8541)
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5499)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5547)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8512)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
java.lang.RuntimeException: Failure delivering result ResultInfo{who=null, request=539, result=-1, data=null} to activity {com.wash.connect/com.wash.connect.MainActivity}: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
    at android.app.ActivityThread.deliverResults(ActivityThread.java:5506)
    at android.app.ActivityThread.handleSendResult(ActivityThread.java:5547)
    at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:51)
    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2307)
    at android.os.Handler.dispatchMessage(Handler.java:106)
    at android.os.Looper.loop(Looper.java:246)
    at android.app.ActivityThread.main(ActivityThread.java:8512)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

Logging from Sentry
```javascript
{
    redux-action: {
        payload: "turning_on", 
        type: "BLUETOOTH_STATE_CHANGE"
     },
     redux-action:{
        payload: "on", 
        type: "BLUETOOTH_STATE_CHANGE"
    },
    exception: {
        RuntimeException: "Illegal callback invocation from native module. This callback type only permits a single invocation from native code."
    }
}
```

It looks like the native module is being initialized twice? Is this something that I am doing wrong?

**Comment by marcosinigaglia** [comment]
You have to init the library only in the one component.
