### ISSUE TITLE
ERROR  Invariant Violation: No callback found with version 8.3.0

### ISSUE THREAD

**Issue by Koxx3** [innoveit/react-native-ble-manager#885]
**Describe the bug**
On read errors (and may be write too), uncachable exceptions are raised.

`ERROR  Invariant Violation: No callback found with cbID 5289 and callID 2644 for  BleManager.read - most likely the callback was already invoked. Args: '["Error reading beb5483e-36e1-4688-b7f5-ea07361b26b6 status=133",null]'
`

**To Reproduce**
Read frequency & disconnect the BLE device

**Expected behavior**
catchable exception.

**Smartphone (please complete the following information):**
 - Device: android
 - OS: android 12
 - react-native-ble-manager version: 8.3.0
 - react-native version: 0.68.2

**Comment by Koxx3** [comment]
I patched to add an try/catch on the disconnect invokes.

Here is the result :
```
2022-08-05 19:25:37.633 17262-17341/com.smartdisplay I/ReactNativeJS: 'bms / fetchAdc : ', '78:21:84:40:D7:82'
2022-08-05 19:25:37.634 17262-17342/com.smartdisplay D/ReactNativeBleManager: Read from: 78:21:84:40:D7:82
2022-08-05 19:25:37.634 17262-17342/com.smartdisplay D/ReactNativeBleManager: Command queue busy
2022-08-05 19:25:37.852 28385-28413/? I/GH.ConnLoggerV2: Session b4626dc0-c3ef-4bbd-80a0-68103a6eeaa2 expired
2022-08-05 19:25:38.124 946-9602/? W/bthal.bqr: ParseLinkQualityRelatedEvt: Appro LSTO , Handle: 0x0040, RSSI_C0: -57, RSSI_C1: -59, TxPw_C0: -128, ReTxPw_C0: -128, TxPw_C1: 9, ReTxPw_C1: 9, BFTx: 0x01, BFReTx: 0x01, DivTx: 0x01, DivReTx: 0x01
2022-08-05 19:25:38.124 946-9602/? I/bthal.flowcontrol: HciEventPreProcess: HCI Event 0xff Opcode 0 Length 225 unhandled by debug_VendorEvent
2022-08-05 19:25:38.125 9503-9672/? W/bt_stack: [WARNING:btif_bqr.cc(390)] Appro LSTO , Handle: 0x0040, DH1, Central, PwLv: 9, RSSI: -57, SNR: 0, UnusedCh: 13, UnidealCh: 0, ReTx: 55, NoRX: 55, NAK: 0, FlowOff: 0, OverFlow: 0, UndFlow: 0
2022-08-05 19:25:38.125 9503-9672/? I/bt_stack: [INFO:btsnoop.cc(338)] clear_l2cap_allowlist: Clearing acceptlist from l2cap channel. conn_handle=64 cid=4:4
2022-08-05 19:25:38.125 9503-9672/? I/bluetooth: system/bt/stack/gap/gap_ble.cc:298 client_connect_cback: No active GAP service found for peer:xx:xx:xx:xx:d7:82 callback:Disconnected
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:3 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:4 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:5 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:6 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:7 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:8 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:9 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:10 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:11 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? I/bt_bta_gattc: system/bt/bta/gatt/bta_gattc_act.cc:1115 bta_gattc_conn_cback: Disconnected att_id:12 transport:le reason:GATT_CONN_TIMEOUT
2022-08-05 19:25:38.126 9503-9672/? W/bt_btm_sec: system/bt/stack/btm/btm_sec.cc:3685 btm_sec_disconnected: Got uncommon disconnection reason:Connection Timeout handle:0x0040
2022-08-05 19:25:38.126 9503-9672/? I/btif_av: system/bt/btif/src/btif_av.cc:3352 btif_av_acl_disconnected: btif_av_acl_disconnected: Peer 78:21:84:40:d7:82 : ACL Disconnected
2022-08-05 19:25:38.126 9503-9672/? I/btif_av: system/bt/btif/src/btif_av.cc:1078 FindOrCreatePeer: BtifAvPeer *BtifAvSource::FindOrCreatePeer(const RawAddress &, tBTA_AV_HNDL): Create peer: peer_address=78:21:84:40:d7:82 bta_handle=0x42 peer_id=1
2022-08-05 19:25:38.126 9503-9672/? I/btif_av: system/bt/btif/src/btif_av.cc:1123 DeleteIdlePeers: DeleteIdlePeers: Deleting idle peer: 78:21:84:40:d7:82 bta_handle=0x42
2022-08-05 19:25:38.127 17262-17278/com.smartdisplay D/BluetoothGatt: onClientConnectionState() - status=0 clientIf=9 device=78:21:84:40:D7:82
2022-08-05 19:25:38.127 17262-17278/com.smartdisplay D/ReactNativeBleManager: onConnectionStateChange to 0 on peripheral: 78:21:84:40:D7:82 with status 0
2022-08-05 19:25:38.127 17262-17278/com.smartdisplay D/ReactNativeBleManager: Calling callback : com.facebook.react.bridge.CallbackImpl@31825f2
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err: java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:26)
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at it.innove.Peripheral.onConnectionStateChange(Peripheral.java:336)
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at android.bluetooth.BluetoothGatt$1$4.run(BluetoothGatt.java:281)
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at android.bluetooth.BluetoothGatt.runOrQueueCallback(BluetoothGatt.java:823)
2022-08-05 19:25:38.128 9503-13562/? E/BtGatt.GattService: readCharacteristic() - No connection for 78:21:84:40:D7:82...
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at android.bluetooth.BluetoothGatt.access$200(BluetoothGatt.java:47)
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at android.bluetooth.BluetoothGatt$1.onClientConnectionState(BluetoothGatt.java:276)
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at android.bluetooth.IBluetoothGattCallback$Stub.onTransact(IBluetoothGattCallback.java:201)
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at android.os.Binder.execTransactInternal(Binder.java:1184)
2022-08-05 19:25:38.128 17262-17278/com.smartdisplay W/System.err:     at android.os.Binder.execTransact(Binder.java:1143)
2022-08-05 19:25:38.129 17262-17278/com.smartdisplay D/BluetoothGatt: cancelOpen() - device: 78:21:84:40:D7:82
```

now, no more annoying React native exception. It's catched before.

**Comment by Koxx3** [comment]
I've created the pull request for the fix :
https://github.com/innoveit/react-native-ble-manager/pull/888

Can you please include the fix in a new release @marcosinigaglia  ?
