### ISSUE TITLE
[Android] App crashes when trying to enable Bluetooth when running in HeadlessJS mode

### ISSUE THREAD

**Issue by vikeri** [innoveit/react-native-ble-manager#90]
When the app is running in the background the `getCurrent` method returns `null` and thus this error is thrown:

```java
E/unknown:React: Exception in native call
  java.lang.NullPointerException: Attempt to invoke virtual method 'void android.app.Activity.startActivityForResult(android.content.Intent, int)' on a null object reference
      at it.innove.BleManager.enableBluetooth(BleManager.java:101)
      at java.lang.reflect.Method.invoke(Native Method)
      at com.facebook.react.bridge.BaseJavaModule$JavaMethod.invoke(BaseJavaModule.java:318)
      at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:158)
      at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
      at android.os.Handler.handleCallback(Handler.java:739)
      at android.os.Handler.dispatchMessage(Handler.java:95)
      at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:31)
      at android.os.Looper.loop(Looper.java:148)
      at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(MessageQueueThreadImpl.java:196)
      at java.lang.Thread.run(Thread.java:818)
```

Not sure if it is possible to enable Bluetooth in the background. If not maybe one should display a warning instead of throwing the error.

**Comment by marcosinigaglia** [comment]
Hi, I never tried to use the module in background, I'll catch this error in the next release. Thanks.
