### ISSUE TITLE
Could not invoke BleManager.scan

### ISSUE THREAD

**Issue by Marvedog** [innoveit/react-native-ble-manager#916]
**Describe the bug**
When running `BleManager.scan` on an Android Nougat device, the app crashes with the following the below error. Have anyone experienced something similar.

```
    java.lang.RuntimeException: Could not invoke BleManager.scan
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loop(Looper.java:154)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:762)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.NoSuchMethodError: No virtual method setLegacy(Z)Landroid/bluetooth/le/ScanSettings$Builder; in class Landroid/bluetooth/le/ScanSettings$Builder; or its super classes (declaration of 'android.bluetooth.le.ScanSettings$Builder' appears in /system/framework/framework.jar)
        at it.innove.LollipopScanManager.scan(LollipopScanManager.java:44)
        at it.innove.BleManager.scan(BleManager.java:203)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228) 
        at java.lang.Thread.run(Thread.java:762) 
```

**To Reproduce**
1. Install the App on an Android Nougat device
2. Setup the `BleManager`
3. Start scan

**Expected behavior**
In our case, this works fine for most other Android devices. Been running the same code on different Android devices with higher API levels for months. Just experienced this the first time we tested everything on an Android Nougat device.

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S6
 - OS: Android Nougat (API 24)
 - react-native-ble-manager version: latest 
 - react-native version: 0.68.4

**Comment by Marvedog** [comment]
Experiencing the same on a newly acquired Android 7.1.1 Sony Xperia as well.

**Comment by Marvedog** [comment]
Found the solution. 

`getLegacy` is only available for Android O and above

https://developer.android.com/reference/android/bluetooth/le/ScanSettings#getLegacy()

This issue can be resolved by adding a check here. Will submit a PR soon... 

https://github.com/innoveit/react-native-ble-manager/blob/master/android/src/main/java/it/innove/LollipopScanManager.java#L42

**Comment by Marvedog** [comment]
#934
