### ISSUE TITLE
android需要权限

### ISSUE THREAD

**Issue by Jack-QMY** [innoveit/react-native-ble-manager#917]
I have configured relevant permissions in AndroidManifest.xml, but Need android.permission.BLUETOOTH_SCAN permission appears during Bluetooth scan ，as follows

java.lang.SecurityException: Need android.permission.BLUETOOTH_SCAN permission for android.content.AttributionSource@55219ad: GattService registerScanner
        at android.os.Parcel.createExceptionOrNull(Parcel.java:2425)
        at android.os.Parcel.createException(Parcel.java:2409)
        at android.os.Parcel.readException(Parcel.java:2392)
        at android.os.Parcel.readException(Parcel.java:2334)
        at android.bluetooth.IBluetoothGatt$Stub$Proxy.registerScanner(IBluetoothGatt.java:1812)
        at android.bluetooth.le.BluetoothLeScanner$BleScanCallbackWrapper.startRegistration(BluetoothLeScanner.java:447)
        at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:292)
        at android.bluetooth.le.BluetoothLeScanner.startScan(BluetoothLeScanner.java:158)
        at it.innove.LollipopScanManager.scan(LollipopScanManager.java:81)
        at it.innove.BleManager.scan(BleManager.java:203)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
        at android.os.Handler.handleCallback(Handler.java:938)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
        at android.os.Looper.loopOnce(Looper.java:210)
        at android.os.Looper.loop(Looper.java:299)
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:228)
        at java.lang.Thread.run(Thread.java:920)

**Comment by Jack-QMY** [comment]
![image](https://user-images.githubusercontent.com/57746139/200247165-7529e697-8f67-4d52-8586-602d2121db85.png)

**Comment by Jack-QMY** [comment]
已经修复
