### ISSUE TITLE
About the crash caused by turning off the receiver's device when Bluetooth is sending information

### ISSUE THREAD

**Issue by Facemax** [innoveit/react-native-ble-manager#989]
**Before open an issue**
- Check the closed issues, your question maybe is not new.
**Describe the bug**
This is crash log ：

FATAL EXCEPTION: main
Process: com.factorytools, PID: 6858
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
	at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:26)
	at it.innove.Peripheral$6.run(Peripheral.java:681)
	at android.os.Handler.handleCallback(Handler.java:966)
	at android.os.Handler.dispatchMessage(Handler.java:110)
	at android.os.Looper.loopOnce(Looper.java:205)
	at android.os.Looper.loop(Looper.java:293)
	at android.app.ActivityThread.main(ActivityThread.java:9596)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:586)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1204)

**To Reproduce**
1. After connecting the bluetooth device, set the timer and send information every second (the content is optional)
2. Turn off the bluetooth of the receiving device, and the simulated device is suddenly offline.
3. Log will Show that blePublish then Error: Device disconnected and crash
4. handleDisconnectedPeripheral Function will work, but it will be delayed or when the app crashes, it will appear at the same time

**Expected behavior**
I hope that when the device suddenly disconnects the Bluetooth connection, the Bluetooth sending function will not crash the app. Can you tell me the method, thank you

**Screenshots**
NULL

**Smartphone (please complete the following information):**
 - Device: HUAWEI Mate 30
 - OS: HarmonyOS 3.0.0
   -"react-native": "0.68.2",
    -"react-native-ble-manager": "^8.4.3",

**Additional context**
I hope that when the device suddenly disconnects the Bluetooth connection, the Bluetooth sending function will not crash the app. Can you tell me the method, thank you

**Comment by marcosinigaglia** [comment]
This issue is stale because it has been open 180 days with no activity. Remove stale label or comment or this will be closed in 7 days.
